### ISSUE TITLE
Incorrect information on "integer" storage in Chapter 3, Data Types, The Number Type, p. 42

### ISSUE THREAD

**Issue by goldsipe** [msfrisbie/professional-javascript-for-web-developers-4e#16]
In Chapter 3, Data Types, The Number Type, p. 42, contains several incorrect statements about "integers" in JavaScript. The previous page correctly states that JavaScript stores numbers in IEEE-754 format. However, there are statements on p. 42 that incorrectly suggest there is some other kind of special storage for integers. For example, there's an incorrect statement that "floating-point values uses twice as much memory as storing integer values." The rest of this paragraph also talks about "integer" distinctions that don't exist.

**Comment by msfrisbie** [comment]
Resolved in new edition
